ironicServerName: DEFINE-SERVER-NAME.IO

## Ironic container image used for all Ironic components
##
image:
  name: jakubdlu/centos-openstack-ironic
  version: rocky-0.0.9
  pullPolicy: IfNotPresent

## Existing persistent volume claim
## make sure the pvc can be cross mounted between the containers
# persistentVolumeClaimName: DEFINE-EXISTING-PV-CLAIM

## _Some_ of the /etc/ironic/ironic.conf
## configuration options.
## If you need more, please extract and create PR.
##
config:
  DEFAULT:
    debug: false
    enabled_hardware_types: ipmi
    auth_strategy: noauth
    enabled_network_interfaces: noop
  api:
    api_workers: 8
  conductor:
    heartbeat_interval: 10
    heartbeat_timeout: 30
    deploy_callback_timeout: 1800
    power_state_sync_max_retries: 3
    automated_clean: false
    clean_callback_timeout: 1800
  database: {}
  deploy:
    enable_ata_secure_erase: false
    erase_devices_priority: 0
    erase_devices_metadata_priority: 0
    power_off_after_deploy_failure: false
    http_root: /storage/httpboot
  dhcp:
    dhcp_provider: none
  pxe:
    images_path: /storage/httpboot/images
    instance_master_path: /storage/httpboot/master-path
    tftp_root: /storage/tftpboot
    tftp_master_path: /storage/tftpboot/master-path
    pxe_append_params: "console=tty0 console=ttyS0,115200 coreos.autologin=tty0"
    ipxe_boot_script: $pybasedir/drivers/modules/boot.ipxe
    ## to enable ipxe, replace values of both following keys
    ipxe_enabled: false
    pxe_config_template: $pybasedir/drivers/modules/pxe_config.template
    # ipxe_enabled: true
    # pxe_config_template: $pybasedir/drivers/modules/ipxe_config.template

api:
  ## Ironic API container name
  ##
  name: api

  ## Ironic API scaling settings
  ##
  replicas: 1

  ## Ironic API ports
  ##
  portInternal: 8080
  portExternal: 6387

  ingress:
    enabled: false
    annotations: {}
    #  kubernetes.io/ingress.class: nginx
    #  kubernetes.io/tls-acme: "true"
    paths: []
    hosts:
      - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  ## Ironic API external IP
  ##
  # externalIPs:
  #   - DEFINE-IP-HERE

  ## Ironic API resources
  ##
  resources:
    requests:
      memory: "8G"
      cpu: "8"
    limits:
      memory: "8G"
      cpu: "8"


httpboot:
  ## Ironic www name
  ##
  name: httpboot

  ## Ironic www scaling
  ##
  replicas: 1

  portInternal: 80
  portExternal: 80

  ingress:
    enabled: false
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    #  kubernetes.io/ingress.class: nginx
    #  kubernetes.io/tls-acme: "true"
    paths: []
    hosts:
      - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  ## Ironic www external IP
  ##
  # externalIPs:
  #   - DEFINE-IP-HERE

  ## Ironic www container image info
  ##
  image:
    name: nginx
    version: 1.13.5-alpine
    pullPolicy: IfNotPresent

  ## Ironic www resources
  ##
  resources:
    requests:
      memory: "2G"
      cpu: "2"
    limits:
      memory: "4G"
      cpu: "4"

mgmt:
  ## Ironic management pod name
  ##
  name: mgmt

  ## Ironic management pod scaling
  ##
  replicas: 1

tftp:
  ## Ironic tftp name
  ##
  name: tftp

  ## Ironic tftp network configuration
  ##
  externalIPs:
    - DEFINE-IP-HERE

  persistence:
    enabled: true
    accessMode: ReadWriteMany
    size: 8Gi
    annotations: {}
  ## make sure the resulted pvc can be cross mounted between the containers
  #  storageClass: "default"

  ## Ironic tftp resources
  ##
  resources:
    requests:
      memory: "2G"
      cpu: "2"
    limits:
      memory: "4G"
      cpu: "4"

  nodeSelector: {}

conductor:
  ## Ironic Conductor name
  ##
  name: conductor

  ## Ironic Conductor scaling
  ##
  replicas: 1

  ## Ironic Conductor resources
  ##
  resources:
    requests:
      memory: "8G"
      cpu: "8"
    limits:
      memory: "8G"
      cpu: "8"

mysql:
  enabled: true
  image: mysql
  imageTag: "5.7.14"
  mysqlUser: ironic
#  mysqlPassword: DEFINE-THIS-SECRET
  mysqlDatabase: ironic
#  mysqlRootPassword: DEFINE-THIS-SECRET
  imagePullPolicy: IfNotPresent
  readinessProbe:
    initialDelaySeconds: 60
  livenessProbe:
    initialDelaySeconds: 120
  persistence:
    enabled: true
    subPath: mysql
  #  existingClaim: DEFINE-EXISTING-PV-CLAIM
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

rabbitmq:
  enabled: true
  replicas: 1
  rabbitmq:
    username: rabbitmq
#    password: DEFINE-THIS-SECRET
  image:
    pullPolicy: IfNotPresent
  persistence:
    enabled: false
