apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openstackIronicStandalone.api.fullname" . }}
  labels:
    app: {{ include "openstackIronicStandalone.name" . }}
    chart: {{ include "openstackIronicStandalone.chart" . }}
    component: {{ .Values.api.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ include "openstackIronicStandalone.name" . }}
      component: {{ .Values.api.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ include "openstackIronicStandalone.api.fullname" . }}
      labels:
        app: {{ include "openstackIronicStandalone.name" . }}
        component: {{ .Values.api.name }}
        release: {{ .Release.Name }}
      annotations:
        configmap-etc-hash: {{ include (print $.Template.BasePath "/etc-configmap.yaml") . | sha256sum }}
    spec:
      template:
        metadata:
          labels:
            app: {{ include "openstackIronicStandalone.name" . }}
            component: {{ .Values.api.name }}
            release: {{ .Release.Name }}
      containers:
        - name: {{ include "openstackIronicStandalone.api.fullname" . }}
          image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        {{- with .Values.api.resources }}
          resources:
{{ toYaml . | indent 12 }}
        {{- end }}
          command:
            - /bin/sh
          args:
            - -c
            - mako-render /etc/ironic/ironic.conf.mako >/tmp/ironic.conf; /usr/bin/ironic-api --config-file /tmp/ironic.conf
          env:
            - name: API_PORT_INTERNAL
              value: {{ .Values.api.portInternal | quote }}
            {{- if .Values.rabbitmq.enabled }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq
                  key: rabbitmq-password
            - name: RABBITMQ_ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq
                  key: rabbitmq-erlang-cookie
            {{- end }}
            {{- if .Values.mariadb.enabled }}
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb
                  {{- if .Values.mariadb.db.user }}
                  key: mariadb-password
                  {{- else }}
                  key: mariadb-root-password
                  {{- end }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.api.portInternal }}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          ports:
            - name: ironic-api
              containerPort: {{ .Values.api.portInternal }}
          volumeMounts:
            - mountPath: /etc/ironic
              name: ironic-etc
              readOnly: true
      volumes:
        - name: ironic-etc
          configMap:
            name: {{ include "openstackIronicStandalone.name" . }}-etc
            defaultMode: 0644
