apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ include "openstackIronicStandalone.mgmt.fullname" . }}
  labels:
    app: {{ include "openstackIronicStandalone.name" . }}
    chart: {{ include "openstackIronicStandalone.chart" . }}
    component: {{ .Values.mgmt.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.api.replicas }}
  template:
    metadata:
      labels:
        app: {{ include "openstackIronicStandalone.name" . }}
        component: {{ .Values.mgmt.name }}
        release: {{ .Release.Name }}
      name: {{ include "openstackIronicStandalone.mgmt.fullname" . }}
      annotations:
        configmap-etc-hash: {{ include (print $.Template.BasePath "/etc-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ include "openstackIronicStandalone.mgmt.fullname" . }}
          image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command: [ "{{ .Values.mgmt.pod_command }}" ]
          args: [ "{{ .Values.mgmt.pod_args }}" ]
          env:
{{ toYaml .Values.mgmt.env | indent 14 }}
          - name: IRONIC_URL
            value: "http://{{ include "openstackIronicStandalone.api.fullname" . }}:{{ .Values.api.portExternal }}/"
          - name: OS_URL
            value: "http://{{ include "openstackIronicStandalone.api.fullname" . }}:{{ .Values.api.portExternal }}/"
          volumeMounts:
            - mountPath: /usr/local/bin/wait-for-mysql.sh
              name: ironic-db-scripts
              subPath: wait-for-mysql.sh
              readOnly: true
            - mountPath: /storage
              name: ironic
            - mountPath: /mnt/mgmt-scripts
              name: ironic
              subPath: mgmt-scripts
            - mountPath: /etc/ironic
              name: ironic-etc
              readOnly: true
      volumes:
        - name: ironic
          persistentVolumeClaim:
            {{- if .Values.persistentVolumeClaimName }}
            claimName: {{ .Values.persistentVolumeClaimName | quote }}
            {{- else }}
            claimName: {{ ( include "openstackIronicStandalone.tftp.fullname" . ) | quote }}
            {{- end }}
        - name: ironic-etc
          configMap:
            name: {{ include "openstackIronicStandalone.name" . }}-etc
        - name: ironic-db-scripts
          configMap:
            name: {{ include "openstackIronicStandalone.name" . }}-db-scripts
            defaultMode: 0755
